build:
  maxIssues: 0

complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
  CyclomaticComplexMethod:
    active: false
  TooManyFunctions:
    active: false
  LargeClass:
    active: false
  NestedBlockDepth:
    threshold: 6
  ComplexCondition:
    threshold: 6

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'
  MatchingDeclarationName:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 180
  WildcardImport:
    active: false
  ReturnCount:
    max: 10
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
  ForbiddenComment:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 5
  UseCheckOrError:
    active: false
  ThrowsCount:
    max: 4

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
  TooGenericExceptionThrown:
    active: false

potential-bugs:
  LateinitUsage:
    active: false

performance:
  SpreadOperator:
    active: false
